const LOGO_PATHS = {

    'POR': '/assets/logos/blazers.png',
    'MIL': '/assets/logos/bucks.png',
    'CHI': '/assets/logos/bulls.png',
    'CLE': '/assets/logos/cavs.png',
    'BOS': '/assets/logos/celtics.png',
    'MEM': '/assets/logos/grizzlies.png',
    'ATL': '/assets/logos/hawks.png',
    'MIA': '/assets/logos/heat.png',
    'CHA': '/assets/logos/hornets.png',
    'UTA': '/assets/logos/jazz.png',
    'SAC': '/assets/logos/kings.png',
    'NYK': '/assets/logos/knicks.png',
    'LAL': '/assets/logos/lakers.png',
    'ORL': '/assets/logos/magic.png',
    'DAL': '/assets/logos/mavs.png',
    'BKN': '/assets/logos/nets.png',
    'DEN': '/assets/logos/nuggets.png',
    'IND': '/assets/logos/pacers.png',
    'NOP': '/assets/logos/pelicans.png',
    'DET': '/assets/logos/pistons.png',
    'TOR': '/assets/logos/raptors.png',
    'HOU': '/assets/logos/rockets.png',
    'PHI': '/assets/logos/sixers.png',
    'SAS': '/assets/logos/spurs.png',
    'PHX': '/assets/logos/suns.png',
    'OKC': '/assets/logos/thunder.png',
    'GSW': '/assets/logos/warriors.png',
    'WAS': '/assets/logos/wizards.png',
    'MIN': '/assets/logos/wolves.png',
    'LAC': '/assets/logos/clippers.png',
}

export default logos = {

    'MIL': require('../../../assets/logos/bucks.png'),
    'POR': require('../../../assets/logos/blazers.png'),
    'CHI': require('../../../assets/logos/bulls.png'),
    'CLE': require('../../../assets/logos/cavs.png'),
    'BOS': require('../../../assets/logos/celtics.png'),
    'MEM': require('../../../assets/logos/grizzlies.png'),
    'ATL': require('../../../assets/logos/hawks.png'),
    'MIA': require('../../../assets/logos/heat.png'),
    'CHA': require('../../../assets/logos/hornets.png'),
    'UTA': require('../../../assets/logos/jazz.png'),
    'SAC': require('../../../assets/logos/kings.png'),
    'NYK': require('../../../assets/logos/knicks.png'),
    'LAL': require('../../../assets/logos/lakers.png'),
    'ORL': require('../../../assets/logos/magic.png'),
    'DAL': require('../../../assets/logos/mavs.png'),
    'BKN': require('../../../assets/logos/nets.png'),
    'DEN': require('../../../assets/logos/nuggets.png'),
    'IND': require('../../../assets/logos/pacers.png'),
    'NOP': require('../../../assets/logos/pelicans.png'),
    'DET': require('../../../assets/logos/pistons.png'),
    'TOR': require('../../../assets/logos/raptors.png'),
    'HOU': require('../../../assets/logos/rockets.png'),
    'PHI': require('../../../assets/logos/sixers.png'),
    'SAS': require('../../../assets/logos/spurs.png'),
    'PHX': require('../../../assets/logos/suns.png'),
    'OKC': require('../../../assets/logos/thunder.png'),
    'GSW': require('../../../assets/logos/warriors.png'),
    'WAS': require('../../../assets/logos/wizards.png'),
    'MIN': require('../../../assets/logos/wolves.png'),
    'LAC': require('../../../assets/logos/clippers.png')

};


